"""Seed canonical_exercise and exercise_alias tables

Revision ID: 0004
Revises: 0003
Create Date: 2026-04-27 20:01:00.000000
"""
import json
from collections.abc import Sequence

from alembic import op
from sqlalchemy import text

revision: str = "0004"
down_revision: str | None = "0003"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

# fmt: off
_EXERCISES = [
    # CHEST
    {"name": "Flat Barbell Bench Press",     "cat": "chest",     "muscles": ["chest","triceps","front_delt"], "equip": ["barbell","bench"],
     "aliases": ["bench press","flat bench","barbell bench press","flat barbell bench","chest press barbell"]},
    {"name": "Incline Barbell Bench Press",  "cat": "chest",     "muscles": ["upper_chest","triceps","front_delt"], "equip": ["barbell","incline_bench"],
     "aliases": ["incline bench press","incline barbell bench","incline barbell press"]},
    {"name": "Decline Barbell Bench Press",  "cat": "chest",     "muscles": ["lower_chest","triceps"], "equip": ["barbell","decline_bench"],
     "aliases": ["decline bench press","decline barbell"]},
    {"name": "Flat Dumbbell Bench Press",    "cat": "chest",     "muscles": ["chest","triceps","front_delt"], "equip": ["dumbbells","bench"],
     "aliases": ["dumbbell bench press","DB bench press","flat DB press","dumbbell chest press"]},
    {"name": "Incline Dumbbell Bench Press", "cat": "chest",     "muscles": ["upper_chest","triceps","front_delt"], "equip": ["dumbbells","incline_bench"],
     "aliases": ["incline DB press","incline dumbbell press","incline dumbell press","incline db bench"]},
    {"name": "Decline Dumbbell Bench Press", "cat": "chest",     "muscles": ["lower_chest","triceps"], "equip": ["dumbbells","decline_bench"],
     "aliases": ["decline DB press","decline dumbbell press"]},
    {"name": "Smith Machine Bench Press",    "cat": "chest",     "muscles": ["chest","triceps"], "equip": ["smith_machine","bench"],
     "aliases": ["smith machine press","smith press","smith bench"]},
    {"name": "Incline Smith Machine Press",  "cat": "chest",     "muscles": ["upper_chest","triceps"], "equip": ["smith_machine","incline_bench"],
     "aliases": ["incline smith press","smith incline press"]},
    {"name": "Hammer Strength Chest Press",  "cat": "chest",     "muscles": ["chest","triceps"], "equip": ["machine"],
     "aliases": ["plate-loaded chest press","machine chest press","iso lateral chest press"]},
    {"name": "Incline Machine Press",        "cat": "chest",     "muscles": ["upper_chest","triceps"], "equip": ["machine"],
     "aliases": ["incline machine chest press"]},
    {"name": "Cable Fly (Low Pulley)",       "cat": "chest",     "muscles": ["chest"], "equip": ["cable_machine"],
     "aliases": ["low cable fly","low pulley cable fly","low cable crossover","cable crossover low"]},
    {"name": "Cable Fly (High Pulley)",      "cat": "chest",     "muscles": ["lower_chest"], "equip": ["cable_machine"],
     "aliases": ["high cable fly","high pulley cable fly","cable crossover","cable crossover high"]},
    {"name": "Pec Deck Fly",                 "cat": "chest",     "muscles": ["chest"], "equip": ["machine"],
     "aliases": ["pec deck","chest fly machine","machine fly","butterfly machine"]},
    {"name": "Dumbbell Fly",                 "cat": "chest",     "muscles": ["chest"], "equip": ["dumbbells","bench"],
     "aliases": ["DB fly","flat dumbbell fly","chest fly dumbbell"]},
    {"name": "Incline Dumbbell Fly",         "cat": "chest",     "muscles": ["upper_chest"], "equip": ["dumbbells","incline_bench"],
     "aliases": ["incline DB fly","incline fly"]},
    {"name": "Push-Up",                      "cat": "chest",     "muscles": ["chest","triceps","front_delt"], "equip": [],
     "aliases": ["pushup","push up","chest push up"]},
    {"name": "Dumbbell Pullover",            "cat": "chest",     "muscles": ["chest","lats"], "equip": ["dumbbells","bench"],
     "aliases": ["DB pullover","pullover","dumbbell pullover bench"]},
    {"name": "Landmine Press",               "cat": "chest",     "muscles": ["upper_chest","front_delt","triceps"], "equip": ["barbell","landmine"],
     "aliases": ["landmine chest press","landmine single arm press"]},

    # BACK
    {"name": "Bent-Over Barbell Row",        "cat": "back",      "muscles": ["lats","rhomboids","rear_delt","biceps"], "equip": ["barbell"],
     "aliases": ["barbell row","BB row","bent over row","overhand barbell row","pronated barbell row"]},
    {"name": "Pendlay Row",                  "cat": "back",      "muscles": ["lats","rhomboids","rear_delt"], "equip": ["barbell"],
     "aliases": ["pendlay","strict barbell row","dead stop row"]},
    {"name": "Single-Arm Dumbbell Row",      "cat": "back",      "muscles": ["lats","rhomboids","biceps"], "equip": ["dumbbells","bench"],
     "aliases": ["DB row","dumbbell row","one arm dumbbell row","single arm row","unilateral DB row"]},
    {"name": "Seated Cable Row",             "cat": "back",      "muscles": ["lats","rhomboids","rear_delt"], "equip": ["cable_machine"],
     "aliases": ["cable row","seated row","low cable row","close-grip cable row","machine row"]},
    {"name": "T-Bar Row",                    "cat": "back",      "muscles": ["lats","rhomboids","rear_delt"], "equip": ["barbell","landmine"],
     "aliases": ["t bar row","landmine row","v-grip row"]},
    {"name": "Chest-Supported Row (Machine)","cat": "back",      "muscles": ["lats","rhomboids","rear_delt"], "equip": ["machine"],
     "aliases": ["chest supported row","supported row","hammer strength row"]},
    {"name": "Meadows Row",                  "cat": "back",      "muscles": ["lats","rhomboids"], "equip": ["barbell","landmine"],
     "aliases": ["meadows row","landmine unilateral row"]},
    {"name": "Lat Pulldown",                 "cat": "back",      "muscles": ["lats","biceps"], "equip": ["cable_machine"],
     "aliases": ["wide grip pulldown","overhead pulldown","pulldown","lat pull down","lat pull-down"]},
    {"name": "Close-Grip Lat Pulldown",      "cat": "back",      "muscles": ["lats","biceps"], "equip": ["cable_machine"],
     "aliases": ["close grip pulldown","v-bar pulldown","neutral grip pulldown"]},
    {"name": "Reverse-Grip Lat Pulldown",    "cat": "back",      "muscles": ["lats","biceps"], "equip": ["cable_machine"],
     "aliases": ["underhand pulldown","supinated pulldown","reverse grip pulldown"]},
    {"name": "Pull-Up",                      "cat": "back",      "muscles": ["lats","biceps","rear_delt"], "equip": ["pull_up_bar"],
     "aliases": ["pullup","pull up","overhand pull up","pronated pull up"]},
    {"name": "Chin-Up",                      "cat": "back",      "muscles": ["lats","biceps"], "equip": ["pull_up_bar"],
     "aliases": ["chinup","chin up","underhand pull up","supinated pull up"]},
    {"name": "Straight-Arm Pulldown",        "cat": "back",      "muscles": ["lats"], "equip": ["cable_machine"],
     "aliases": ["straight arm cable pulldown","stiff arm pulldown","lat prayer"]},
    {"name": "Conventional Deadlift",        "cat": "back",      "muscles": ["hamstrings","glutes","lats","erectors"], "equip": ["barbell"],
     "aliases": ["deadlift","conventional deadlift","barbell deadlift"]},
    {"name": "Romanian Deadlift",            "cat": "back",      "muscles": ["hamstrings","glutes","erectors"], "equip": ["barbell"],
     "aliases": ["RDL","romanian deadlift","barbell RDL","stiff leg deadlift barbell"]},
    {"name": "Sumo Deadlift",                "cat": "back",      "muscles": ["hamstrings","glutes","adductors","lats"], "equip": ["barbell"],
     "aliases": ["sumo deadlift","wide stance deadlift"]},
    {"name": "Rack Pull",                    "cat": "back",      "muscles": ["lats","traps","erectors"], "equip": ["barbell","rack"],
     "aliases": ["rack pull","partial deadlift","pin pull"]},
    {"name": "Good Morning",                 "cat": "back",      "muscles": ["hamstrings","erectors","glutes"], "equip": ["barbell"],
     "aliases": ["good morning","barbell good morning"]},
    {"name": "Back Extension (Hyperextension)","cat":"back",     "muscles": ["erectors","glutes","hamstrings"], "equip": ["machine"],
     "aliases": ["hyperextension","back extension","45 degree back extension","roman chair"]},
    {"name": "Barbell Shrug",                "cat": "back",      "muscles": ["traps"], "equip": ["barbell"],
     "aliases": ["shrug","barbell shrug","BB shrug","traps shrug"]},
    {"name": "Dumbbell Shrug",               "cat": "back",      "muscles": ["traps"], "equip": ["dumbbells"],
     "aliases": ["DB shrug","dumbbell shrug"]},
    {"name": "Face Pull",                    "cat": "back",      "muscles": ["rear_delt","rhomboids","rotator_cuff"], "equip": ["cable_machine"],
     "aliases": ["face pull","cable face pull","rope face pull"]},

    # LEGS
    {"name": "Back Squat",                   "cat": "legs",      "muscles": ["quads","glutes","hamstrings"], "equip": ["barbell","rack"],
     "aliases": ["squat","barbell squat","back squat barbell","high bar squat","low bar squat"]},
    {"name": "Front Squat",                  "cat": "legs",      "muscles": ["quads","glutes"], "equip": ["barbell","rack"],
     "aliases": ["front squat","front rack squat"]},
    {"name": "Goblet Squat",                 "cat": "legs",      "muscles": ["quads","glutes"], "equip": ["dumbbells","kettlebell"],
     "aliases": ["goblet squat","dumbbell goblet squat","KB goblet squat"]},
    {"name": "Hack Squat (Machine)",         "cat": "legs",      "muscles": ["quads","glutes"], "equip": ["machine"],
     "aliases": ["hack squat","machine hack squat","leg press hack squat"]},
    {"name": "Leg Press",                    "cat": "legs",      "muscles": ["quads","glutes","hamstrings"], "equip": ["machine"],
     "aliases": ["leg press machine","45 degree leg press","plate loaded leg press"]},
    {"name": "Leg Extension",               "cat": "legs",      "muscles": ["quads"], "equip": ["machine"],
     "aliases": ["leg extension machine","quad extension","knee extension"]},
    {"name": "Lying Leg Curl",              "cat": "legs",      "muscles": ["hamstrings"], "equip": ["machine"],
     "aliases": ["leg curl","lying leg curl machine","hamstring curl","hamstring curl lying"]},
    {"name": "Seated Leg Curl",             "cat": "legs",      "muscles": ["hamstrings"], "equip": ["machine"],
     "aliases": ["seated hamstring curl","seated leg curl machine"]},
    {"name": "Nordic Hamstring Curl",       "cat": "legs",      "muscles": ["hamstrings"], "equip": [],
     "aliases": ["nordic curl","nordic hamstring","eccentric hamstring curl"]},
    {"name": "Romanian Deadlift (Dumbbell)","cat": "legs",      "muscles": ["hamstrings","glutes"], "equip": ["dumbbells"],
     "aliases": ["dumbbell RDL","DB RDL","dumbbell romanian deadlift","stiff leg deadlift dumbbell"]},
    {"name": "Bulgarian Split Squat",       "cat": "legs",      "muscles": ["quads","glutes"], "equip": ["dumbbells"],
     "aliases": ["split squat","RFESS","Bulgarian split squat","rear foot elevated split squat"]},
    {"name": "Walking Lunge",               "cat": "legs",      "muscles": ["quads","glutes","hamstrings"], "equip": ["dumbbells"],
     "aliases": ["lunge","walking lunges","dumbbell lunge","walking dumbbell lunge"]},
    {"name": "Reverse Lunge",               "cat": "legs",      "muscles": ["quads","glutes"], "equip": ["dumbbells"],
     "aliases": ["reverse lunge","step back lunge","backward lunge"]},
    {"name": "Step-Up",                     "cat": "legs",      "muscles": ["quads","glutes"], "equip": ["dumbbells","bench"],
     "aliases": ["step up","box step up","dumbbell step up"]},
    {"name": "Hip Thrust",                  "cat": "legs",      "muscles": ["glutes","hamstrings"], "equip": ["barbell","bench"],
     "aliases": ["hip thrust","barbell hip thrust","glute bridge barbell","barbell glute bridge"]},
    {"name": "Glute Bridge",                "cat": "legs",      "muscles": ["glutes","hamstrings"], "equip": [],
     "aliases": ["glute bridge","bodyweight glute bridge","floor glute bridge"]},
    {"name": "Cable Glute Kickback",        "cat": "legs",      "muscles": ["glutes"], "equip": ["cable_machine"],
     "aliases": ["glute kickback","cable kickback","donkey kick cable"]},
    {"name": "Standing Calf Raise",         "cat": "legs",      "muscles": ["calves"], "equip": ["machine"],
     "aliases": ["calf raise","standing calf raise machine","calf press standing"]},
    {"name": "Seated Calf Raise",           "cat": "legs",      "muscles": ["soleus","calves"], "equip": ["machine"],
     "aliases": ["seated calf raise machine","seated calf press"]},
    {"name": "Calf Raise (Leg Press)",      "cat": "legs",      "muscles": ["calves"], "equip": ["machine"],
     "aliases": ["leg press calf raise","calf press leg press"]},
    {"name": "Adductor Machine",            "cat": "legs",      "muscles": ["adductors"], "equip": ["machine"],
     "aliases": ["inner thigh machine","adductor","hip adduction machine"]},
    {"name": "Abductor Machine",            "cat": "legs",      "muscles": ["abductors","glutes"], "equip": ["machine"],
     "aliases": ["outer thigh machine","abductor","hip abduction machine"]},
    {"name": "Sissy Squat",                 "cat": "legs",      "muscles": ["quads"], "equip": [],
     "aliases": ["sissy squat","sissy squat machine"]},

    # SHOULDERS
    {"name": "Overhead Barbell Press",      "cat": "shoulders", "muscles": ["front_delt","side_delt","triceps"], "equip": ["barbell"],
     "aliases": ["OHP","overhead press","military press","barbell overhead press","standing press","BB OHP"]},
    {"name": "Seated Dumbbell Shoulder Press","cat":"shoulders","muscles": ["front_delt","side_delt","triceps"], "equip": ["dumbbells","bench"],
     "aliases": ["dumbbell shoulder press","DB shoulder press","seated DB press","seated dumbbell press"]},
    {"name": "Arnold Press",                "cat": "shoulders", "muscles": ["front_delt","side_delt","triceps"], "equip": ["dumbbells"],
     "aliases": ["arnold press","rotating dumbbell press"]},
    {"name": "Machine Shoulder Press",      "cat": "shoulders", "muscles": ["front_delt","side_delt","triceps"], "equip": ["machine"],
     "aliases": ["machine shoulder press","shoulder press machine","plate loaded shoulder press"]},
    {"name": "Lateral Raise (Dumbbell)",    "cat": "shoulders", "muscles": ["side_delt"], "equip": ["dumbbells"],
     "aliases": ["lateral raise","dumbbell lateral raise","DB lateral raise","side raise","side lateral raise"]},
    {"name": "Lateral Raise (Cable)",       "cat": "shoulders", "muscles": ["side_delt"], "equip": ["cable_machine"],
     "aliases": ["cable lateral raise","cable side raise","low pulley lateral raise"]},
    {"name": "Lateral Raise (Machine)",     "cat": "shoulders", "muscles": ["side_delt"], "equip": ["machine"],
     "aliases": ["machine lateral raise","machine side raise","lateral raise machine"]},
    {"name": "Front Raise (Dumbbell)",      "cat": "shoulders", "muscles": ["front_delt"], "equip": ["dumbbells"],
     "aliases": ["front raise","dumbbell front raise","DB front raise"]},
    {"name": "Front Raise (Cable)",         "cat": "shoulders", "muscles": ["front_delt"], "equip": ["cable_machine"],
     "aliases": ["cable front raise","front cable raise"]},
    {"name": "Rear Delt Fly (Dumbbell)",    "cat": "shoulders", "muscles": ["rear_delt","rhomboids"], "equip": ["dumbbells"],
     "aliases": ["rear delt fly","bent over lateral raise","reverse fly","DB rear delt fly","reverse dumbbell fly"]},
    {"name": "Rear Delt Fly (Machine)",     "cat": "shoulders", "muscles": ["rear_delt","rhomboids"], "equip": ["machine"],
     "aliases": ["pec deck reverse fly","rear delt machine","reverse pec deck","machine reverse fly"]},
    {"name": "Rear Delt Cable Fly",         "cat": "shoulders", "muscles": ["rear_delt","rhomboids"], "equip": ["cable_machine"],
     "aliases": ["cable reverse fly","cable rear delt fly","cross body rear delt"]},
    {"name": "Upright Row (Barbell)",       "cat": "shoulders", "muscles": ["side_delt","traps","biceps"], "equip": ["barbell"],
     "aliases": ["upright row","barbell upright row","BB upright row"]},
    {"name": "Upright Row (Cable)",         "cat": "shoulders", "muscles": ["side_delt","traps"], "equip": ["cable_machine"],
     "aliases": ["cable upright row"]},

    # ARMS
    {"name": "Barbell Curl",               "cat": "arms",      "muscles": ["biceps","brachialis"], "equip": ["barbell"],
     "aliases": ["BB curl","barbell bicep curl","straight bar curl"]},
    {"name": "EZ-Bar Curl",                "cat": "arms",      "muscles": ["biceps","brachialis"], "equip": ["ez_bar"],
     "aliases": ["EZ bar curl","ez curl","cambered bar curl","preacher EZ curl"]},
    {"name": "Alternating Dumbbell Curl",  "cat": "arms",      "muscles": ["biceps"], "equip": ["dumbbells"],
     "aliases": ["dumbbell curl","DB curl","alternating curl","standing dumbbell curl","bicep curl"]},
    {"name": "Hammer Curl",                "cat": "arms",      "muscles": ["biceps","brachialis","brachioradialis"], "equip": ["dumbbells"],
     "aliases": ["hammer curl","neutral grip curl","dumbbell hammer curl"]},
    {"name": "Incline Dumbbell Curl",      "cat": "arms",      "muscles": ["biceps"], "equip": ["dumbbells","incline_bench"],
     "aliases": ["incline curl","incline DB curl","incline bicep curl"]},
    {"name": "Concentration Curl",         "cat": "arms",      "muscles": ["biceps"], "equip": ["dumbbells"],
     "aliases": ["concentration curl","seated concentration curl"]},
    {"name": "Preacher Curl (Machine)",    "cat": "arms",      "muscles": ["biceps"], "equip": ["machine"],
     "aliases": ["preacher curl","preacher machine","machine preacher curl"]},
    {"name": "Spider Curl",                "cat": "arms",      "muscles": ["biceps"], "equip": ["dumbbells","barbell"],
     "aliases": ["spider curl","prone incline curl"]},
    {"name": "Cable Curl",                 "cat": "arms",      "muscles": ["biceps"], "equip": ["cable_machine"],
     "aliases": ["cable bicep curl","low pulley curl","cable bicep","standing cable curl"]},
    {"name": "Bayesian Curl",              "cat": "arms",      "muscles": ["biceps"], "equip": ["cable_machine"],
     "aliases": ["bayesian curl","cable curl behind back","behind back cable curl"]},
    {"name": "Reverse Curl",               "cat": "arms",      "muscles": ["brachioradialis","brachialis"], "equip": ["barbell","dumbbells"],
     "aliases": ["reverse curl","overhand curl","pronated curl"]},
    {"name": "Zottman Curl",               "cat": "arms",      "muscles": ["biceps","brachioradialis"], "equip": ["dumbbells"],
     "aliases": ["zottman curl"]},
    {"name": "Tricep Pressdown (Bar)",     "cat": "arms",      "muscles": ["triceps"], "equip": ["cable_machine"],
     "aliases": ["pressdown","straight bar pressdown","tricep pushdown","cable pressdown","bar pressdown","tricep pressdown"]},
    {"name": "Tricep Pressdown (Rope)",    "cat": "arms",      "muscles": ["triceps"], "equip": ["cable_machine"],
     "aliases": ["rope pressdown","rope pushdown","tricep rope pushdown","rope tricep pressdown"]},
    {"name": "Overhead Tricep Extension (Cable)","cat":"arms",  "muscles": ["triceps"], "equip": ["cable_machine"],
     "aliases": ["overhead cable extension","overhead tricep cable","cable overhead extension","cable French press"]},
    {"name": "Overhead Tricep Extension (Dumbbell)","cat":"arms","muscles": ["triceps"], "equip": ["dumbbells"],
     "aliases": ["overhead dumbbell extension","overhead DB extension","dumbbell French press","French press dumbbell"]},
    {"name": "Skull Crusher",              "cat": "arms",      "muscles": ["triceps"], "equip": ["ez_bar","barbell"],
     "aliases": ["skull crusher","EZ bar skull crusher","lying tricep extension","skull crushers"]},
    {"name": "Close-Grip Bench Press",     "cat": "arms",      "muscles": ["triceps","chest"], "equip": ["barbell","bench"],
     "aliases": ["close grip bench","CGBP","close grip press","narrow grip bench"]},
    {"name": "Tricep Dip",                 "cat": "arms",      "muscles": ["triceps","chest","front_delt"], "equip": ["dip_bars"],
     "aliases": ["dip","tricep dip","weighted dip","bodyweight dip","chest dip"]},
    {"name": "Kickback (Dumbbell)",        "cat": "arms",      "muscles": ["triceps"], "equip": ["dumbbells"],
     "aliases": ["tricep kickback","dumbbell kickback","DB kickback"]},
    {"name": "Single-Arm Tricep Pressdown","cat": "arms",      "muscles": ["triceps"], "equip": ["cable_machine"],
     "aliases": ["single arm pressdown","unilateral pressdown","one arm pressdown"]},
    {"name": "Floor Press",                "cat": "arms",      "muscles": ["triceps","chest"], "equip": ["barbell","dumbbells"],
     "aliases": ["floor press","barbell floor press","dumbbell floor press"]},
    {"name": "Wrist Curl",                 "cat": "arms",      "muscles": ["forearms"], "equip": ["barbell","dumbbells"],
     "aliases": ["wrist curl","palms up wrist curl","forearm curl"]},

    # CORE
    {"name": "Plank",                      "cat": "core",      "muscles": ["core","transverse_abdominis"], "equip": [],
     "aliases": ["plank","forearm plank","prone plank"]},
    {"name": "Ab Wheel Rollout",           "cat": "core",      "muscles": ["core","lats"], "equip": ["ab_wheel"],
     "aliases": ["ab wheel","ab rollout","rollout","ab roller"]},
    {"name": "Cable Crunch",               "cat": "core",      "muscles": ["rectus_abdominis"], "equip": ["cable_machine"],
     "aliases": ["cable crunch","rope crunch","kneeling cable crunch"]},
    {"name": "Hanging Leg Raise",          "cat": "core",      "muscles": ["rectus_abdominis","hip_flexors"], "equip": ["pull_up_bar"],
     "aliases": ["hanging leg raise","hanging knee raise","HLR"]},
    {"name": "Decline Crunch",             "cat": "core",      "muscles": ["rectus_abdominis"], "equip": ["decline_bench"],
     "aliases": ["decline crunch","decline sit-up","weighted decline crunch"]},
    {"name": "Russian Twist",              "cat": "core",      "muscles": ["obliques"], "equip": [],
     "aliases": ["russian twist","seated twist","oblique twist"]},
    {"name": "Side Plank",                 "cat": "core",      "muscles": ["obliques","core"], "equip": [],
     "aliases": ["side plank","lateral plank"]},
    {"name": "Dead Bug",                   "cat": "core",      "muscles": ["core","transverse_abdominis"], "equip": [],
     "aliases": ["dead bug"]},
    {"name": "Hollow Hold",                "cat": "core",      "muscles": ["core","rectus_abdominis"], "equip": [],
     "aliases": ["hollow hold","hollow body hold"]},
    {"name": "V-Up",                       "cat": "core",      "muscles": ["rectus_abdominis","hip_flexors"], "equip": [],
     "aliases": ["v up","v-up","jackknife"]},
    {"name": "Lying Leg Raise",            "cat": "core",      "muscles": ["rectus_abdominis","hip_flexors"], "equip": [],
     "aliases": ["lying leg raise","flat leg raise"]},
    {"name": "Cable Woodchop",             "cat": "core",      "muscles": ["obliques","core"], "equip": ["cable_machine"],
     "aliases": ["cable woodchop","cable chop","rotational cable woodchop"]},
    {"name": "Pallof Press",               "cat": "core",      "muscles": ["core","obliques"], "equip": ["cable_machine"],
     "aliases": ["pallof press","anti-rotation press","cable anti rotation"]},
    {"name": "Dragon Flag",                "cat": "core",      "muscles": ["core","rectus_abdominis"], "equip": ["bench"],
     "aliases": ["dragon flag"]},

    # CARDIO
    {"name": "Incline Treadmill Walk",     "cat": "cardio",    "muscles": [], "equip": ["treadmill"],
     "aliases": ["incline walk","incline treadmill","treadmill incline walk","inclined walking"]},
    {"name": "Treadmill Run",              "cat": "cardio",    "muscles": [], "equip": ["treadmill"],
     "aliases": ["treadmill","treadmill running","running treadmill","jogging treadmill"]},
    {"name": "Stationary Bike (Steady State)","cat":"cardio",  "muscles": [], "equip": ["stationary_bike"],
     "aliases": ["stationary bike","bike cardio","cycling steady state","stationary bicycle"]},
    {"name": "Stationary Bike (HIIT)",     "cat": "cardio",    "muscles": [], "equip": ["stationary_bike"],
     "aliases": ["bike HIIT","cycling intervals","spin bike HIIT","interval cycling"]},
    {"name": "Rowing Machine",             "cat": "cardio",    "muscles": ["back","legs","core"], "equip": ["rower"],
     "aliases": ["rowing","rower","erg","ergometer","concept2"]},
    {"name": "Elliptical",                 "cat": "cardio",    "muscles": [], "equip": ["elliptical"],
     "aliases": ["elliptical machine","cross trainer"]},
    {"name": "Stair Climber",              "cat": "cardio",    "muscles": ["glutes","quads","calves"], "equip": ["stair_climber"],
     "aliases": ["stair climber","step mill","stairmaster","step master"]},
    {"name": "Battle Ropes",               "cat": "cardio",    "muscles": ["shoulders","core"], "equip": ["battle_ropes"],
     "aliases": ["battle ropes","ropes","heavy ropes"]},
    {"name": "Kettlebell Swing",           "cat": "cardio",    "muscles": ["glutes","hamstrings","core"], "equip": ["kettlebell"],
     "aliases": ["KB swing","kettlebell swing","two hand swing","Russian swing"]},
    {"name": "Jump Rope",                  "cat": "cardio",    "muscles": [], "equip": ["jump_rope"],
     "aliases": ["jump rope","skipping","skip rope"]},
]
# fmt: on


def upgrade() -> None:
    conn = op.get_bind()
    for ex in _EXERCISES:
        row = conn.execute(
            text(
                "INSERT INTO canonical_exercise (name, category, primary_muscles, equipment) "
                "VALUES (:name, :cat, CAST(:muscles AS jsonb), CAST(:equip AS jsonb)) RETURNING id"
            ),
            {"name": ex["name"], "cat": ex["cat"], "muscles": json.dumps(ex["muscles"]), "equip": json.dumps(ex["equip"])},
        ).fetchone()
        canonical_id = row[0]
        for alias in ex.get("aliases", []):
            conn.execute(
                text(
                    "INSERT INTO exercise_alias (canonical_exercise_id, alias, source) "
                    "VALUES (:cid, :alias, 'seed') ON CONFLICT DO NOTHING"
                ),
                {"cid": str(canonical_id), "alias": alias},
            )


def downgrade() -> None:
    op.execute("DELETE FROM exercise_alias WHERE source = 'seed'")
    op.execute("DELETE FROM canonical_exercise WHERE is_user_created = FALSE")
